export const TOKEN_TYPE = {
    LPARENTHESIS: '(',
    RPARENTHESIS: ')',
    LBRACKET: '[',
    RBRACKET: ']',
    HYPHEN: '-',
    LBRACE: '{',
    RBRACE: '}',
    STAR: '*',
    PLUS: '+',
    OR: '|',
    COMMA: ',',
    ALTER: '?',
    END: 'EOF',
    EMPTY: 'ε',
    BLANK: ' ',
    ESCAPE: '\\',
    EXTEND: '\d\w',
    UNKNOWN: 'unknown',
    REGCHAR: 'a-z0-9_ \n\t\r',
};